### ISSUE TITLE
Git Bash not recognizing Flask on Tammir's PC

### ISSUE THREAD

**Issue by Thinnawi03** [rhinnawi/brothers_project#15]
python running but wont find/recognize flask (env does not seem to work)

**Comment by rhinnawi** [comment]
#!/usr/bin/env python
^Add this to the top of python scripts. Also better understand what this does

**Comment by rhinnawi** [comment]
Set up venv on Windows in the project folder for Tammir to run it

**Comment by rhinnawi** [comment]
Need to set up requirements.txt

**Comment by rhinnawi** [comment]
Make sure Tammir has updated version of Python, pip
